version: "3.8"

services:
  auth-app:
    container_name: auth-app_dev
    image: auth-app_dev
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    ports:
      - "0.0.0.0:8082:8082"
    volumes:
      - ./src:/app/src
    environment:
      CHOKIDAR_USEPOLLING: "true"